modLoader = "javafml"
loaderVersion = "[4,)"
license = "GNU"
issueTrackerURL = "https://github.com/NickMesser/Mystical-Index/issues"

[[mods]]
modId = "mystical_index"
version = "${version}"
displayName = "Mystical Index"
description = '''
Magical Storage or something like that.
'''
authors = "Nick Messer"
logoFile = "assets/mystical_index/icon.png"

[[dependencies.mystical_index]]
modId = "neoforge"
type = "required"
versionRange = "[26.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mystical_index]]
modId = "minecraft"
type = "required"
versionRange = "[26.1.2,26.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mystical_index]]
modId = "architectury"
type = "required"
versionRange = "[20.0.12,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "mystical_index.mixins.json"

[[mixins]]
config = "mystical_index.neoforge.mixins.json"
